
server:
  port : 5000

logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Badawada123
    url: jdbc:postgresql://blogdbb.czdyytgj3kli.ap-south-1.rds.amazonaws.com:5432/blogdb
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  

  
