server:
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  file:
    name: src/main/resources/applog.log
    